### ISSUE TITLE
Deprecated Models

### ISSUE THREAD

**Issue by Epoche-Napoleon** [netresearch/t3x-cowriter#17]
Hello,

since 04.01.2024 the models ada, curie, davinci and babbage have been switched off by OpenAI. See here: https://platform.openai.com/docs/deprecations. 
The following error message appears in CKEditor:
Error: { "error": { "message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }

Are there plans to switch to another language model?

**Comment by madeinnature** [comment]
Hello,

> (...) "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }
> (...)

That worked for me: 
open typo3conf/ext/t3_cowriter/Resources/Public/JavaScript/Plugins/cowriter/plugin.js
search for "text-davinci-003"
replace with: "gpt-3.5-turbo-instruct"

**Comment by Gitsko** [comment]
Hi @olagwin,

can you change the model in die Plugin ?

**Comment by olagwin** [comment]
Hi  @Thoemel42 

can you please review the changes (pull request)? Especially if the models are now correct.
I used the solution of @Epoche-Napoleon (thank you for that) and additionally changed the labels in the select and removed text-ada and text-babbage, since as I understand https://platform.openai.com/docs/deprecations there is no explizit replacement for them.

fyi @Epoche-Napoleon and @madeinnature : at the moment we are working on getting this extension ready for v12. With this we will also redo the handling with the models, so that it always offers only current models.

**Comment by olagwin** [comment]
New release made for that. Release in TER to follow.

**Comment by TheDevMinerTV** [comment]
We've released v1.2.5 on TER which includes this fix
